UPDATE CRM_USER_LOGIN
SET STATUS = 'FALSE' , USER_LOGIN_ID = CONCAT('$user_id', '_bkp')
WHERE CUSTOMER_ID IN
(SELECT CUSTOMER_ID  FROM CRM_USER_INVITE
WHERE USER_LOGIN_ID = '$user_id'
AND  INVITE_TYPE = 'Y' AND ACTION_TYPE_CODE ='GUEST' AND  CUSTOMER_ID IS NOT NULL )