insert into HCMP_LOOKUP_PINCODE (LOOKUP_ID,LOOKUP_TYPE,LOOKUP_CODE,LOOKUP_VALUE,PARENT_LOOKUP_ID,DESCRIPTION,FLEX1,FLEX2,FLEX3

,FLEX4,FLEX5,ENABLED_FLAG,START_DATE_ACTIVE,END_DATE_ACTIVE,CREATED_BY,CREATION_DATE,LAST_UPDATED_BY,LAST_UPDATE_DATE)

values (HCMP_LOOKUP_PINCODE_SEQ.nextval,'LOCATION_NEW','Central Delhi','Central Delhi',89175,null,'110503',null,'No',null,null,'Y'

,sysdate,null,'Admin.Admin',sysdate,null,null);