--SELECT USER_LOGIN_ID,CUSTOMER_ID,STATUS
--FROM CRM_USER_LOGIN
--WHERE CUSTOMER_ID IN
--(SELECT CUSTOMER_ID
--FROM CRM_USER_INVITE
--WHERE USER_LOGIN_ID LIKE '%$user_id%'
--AND  INVITE_TYPE = 'Y' AND ACTION_TYPE_CODE ='GUEST' AND  CUSTOMER_ID IS NOT NULL );
SELECT cul.USER_LOGIN_ID,cul.CUSTOMER_ID,cul.STATUS,cui.ACTION_TYPE_CODE
FROM CRM_USER_LOGIN cul,CRM_USER_INVITE  cui
WHERE cul.CUSTOMER_ID = cui.CUSTOMER_ID
AND  cui.USER_LOGIN_ID LIKE '%$user_id%'
AND  cul.ORG_CUSTOMER_ID = 636
AND  cui.INVITE_TYPE = 'Y'
AND cui.ACTION_TYPE_CODE ='GUEST'
AND  cui.CUSTOMER_ID IS NOT NULL