UPDATE_ALERT_PATH = "src/sql/update/update_alert.sql"
SELECT_ALERT_PATH = "src/sql/select/select_alert.sql"
SELECT_RULE_PATH = "src/sql/select/select_rule.sql"
UPDATE_RULE_PATH = "src/sql/update/update_rule.sql"
UPDATE_RULE_MASTER_PATH = "src/sql/update/update_rule_def_master.sql"
ALERT_SIZE = 5
RULE_SIZE = 5
MAX_ALERT_ALLOWED = 10
MAX_RULE_ALLOWED = 10
DISPLAY_ALERT_MSG = "Enter Alert Name"
WARNING = "warning"
SUCCESS = "success"
ERROR = "danger"
DB_CONFIG_PATH = "src/config/db_config.json"
